### ISSUE TITLE
Resource upload

### ISSUE THREAD

**Issue by eblondel** [eblondel/geonode4R#3]

**Comment by eblondel** [comment]
@kikislater this repository is a draft R package build to provide an R client to the GeoNode Django web API.

In this ticket i've referenced the method to upload a resource, and tested it vs. a shapefile. It works well, however, when I try to push together an ISO 19115/19139 XML file (which is the encoded in the payload as "xml_file" according to https://docs.geonode.org/en/master/devel/api/usage/index.html#resource-upload), the method returns a status 200, but the dataset is not found in the target Geonode.

Do you know if they are specific issues/hints to know to make it work?

FYI, after resolving this, we will be able to plug a first action for Geonode upload into [geoflow](https://github.com/r-geoflow/geoflow)

cc @juldebar

**Comment by kikislater** [comment]
Nice ! 
I have some ideas but I will test before ...

**Comment by eblondel** [comment]
Issue reported at https://github.com/GeoNode/geonode/issues/10762
